### ISSUE TITLE
Boadcast message to all whatsapp contacts

### ISSUE THREAD

**Issue by aabdelrahmanm** [guru9493/WhatsppIt#3]
Hi,

I've checked your github project for whatsapp.

Looks quit interesting, I'm looking for a freelancer to build something like what you did and I believe you will be the best candidate for this project. 

Hope we could work together, I could hire you on  freelancer.com, toptal, upwork or any other way that looks convenient with you. 

Simply I'm looking for an applet or chrome extension that use web.whatsapp.com to broadcast message to all contacts in my contact list.

Please let me know what do you think.

Kind Regards,
Ahmed

**Comment by guru9493** [comment]
Hi Ahmed,

Thank you for your interest in our project. As I can see from your Issue comments, If you need something to broadcast a message to all Whatsapp contacts, I think whatsapp has already an option to broadcast a message which will be received by all the persons who has your number added as their contact.

If you need something other than this,Please contact me at guru9794[@]gmail[.]com with your complete requirements and scope of project. We are looking forward to work with you.

I'm closing this issue. For further communication please drop me a mail.

Regards,
Guru
